version: '3.9'

services:
  web:
    build: .
    container_name: cinarra_web
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: cinarra_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
