name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose up -d --build

      - name: Wait for server to start
        run: sleep 10

      - name: Check app responds
        run: curl -f http://localhost:8080

      - name: Shut down Docker Compose
        run: docker compose down
