name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start app in background
        run: |
          nohup python3 app/main.py &

      - name: Wait for server to start
        run: sleep 5

      - name: Check app responds
        run: curl -f http://localhost:8080

      - name: Stop app
        run: |
          pkill -f "python3 app/main.py" || true
